# Generated by Django 3.2.5 on 2021-07-12 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_level', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_type', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_up_stage', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('region', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('id_number', models.CharField(blank=True, max_length=30)),
                ('are_you_employed', models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], default='Yes', max_length=5)),
                ('start_up_name', models.CharField(blank=True, max_length=100)),
                ('number_of_founders', models.IntegerField()),
                ('about_the_owner', models.TextField()),
                ('full_month_dedication', models.CharField(choices=[('Yes', 'Yes'), ('NO', 'No')], default='Yes', max_length=5)),
                ('slug', models.SlugField(unique=True)),
                ('id_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.idtype')),
                ('level_of_education', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.education')),
                ('start_up_stages', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.stage')),
            ],
        ),
    ]
